<?php /** @var $block \Magebit\PageListWidget\Block\Widget\PageList */ ?>

<div class="widget-page-list">
    <?php if ($block->getTitle()): ?>
        <h2><?php echo $block->escapeHtml($block->getTitle()); ?></h2>
    <?php endif; ?>

    <ul>
        <?php foreach ($block->getCmsPages() as $page): ?>
            <li>
                <a href="<?php echo $block->getUrl($page->getIdentifier()); ?>">
                    <?php echo $block->escapeHtml($page->getTitle()); ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
