<?php
/** @var Magebit\Faq\Block\FaqList $block */
$faqCollection = $block->getFaqList();
?>

<div id="faq-container" class="faq-container">
    <?php foreach ($faqCollection as $faq): ?>
        <div class="faq-collapsible" data-role="collapsible">
            <div class="faq-title" data-role="trigger">
                <span class="faq-title-span"><?= $block->escapeHtml($faq->getQuestion()); ?></span>
            </div>
            <div class="faq-content" data-role="content">
                <p><?= nl2br($block->escapeHtml($faq->getAnswer())); ?></p>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<script type="text/x-magento-init">
    {
        "#faq-container": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "faqAccordion": {
                        "component": "faqAccordion"
                    }
                }
            }
        }
    }
</script>
