<div class="block block-dashboard-orders w-full border border-paleGray">
    <?php
    $_orders = $block->getOrders();
    $count = count($_orders);
    ?>
    <div class="block-title order p-8 text-xl">
        <strong><?= $block->escapeHtml(__('Pēdējie pasūtījumi')) ?></strong>
    </div>
    <div class="block-content">
        <?= $block->getChildHtml() ?>
        <?php if ($count > 0) : ?>
            <div class="table-wrapper orders-recent">
                <table class="data table table-order-items recent w-full" id="my-orders-table">
                    <thead>
                        <tr class="h-12 px-4 bg-customBlue text-white text-xs">
                            <th scope="col" class="col id"><?= $block->escapeHtml(__('PASŪTĪJUMA NR.')) ?></th>
                            <th scope="col" class="col date"><?= $block->escapeHtml(__('DATUMS')) ?></th>
                            <th scope="col" class="col shipping"><?= $block->escapeHtml(__('PASŪTĪTĀJS')) ?></th>
                            <th scope="col" class="col total"><?= $block->escapeHtml(__('SUMMA')) ?></th>
                            <th scope="col" class="col status"><?= $block->escapeHtml(__('STATUSS')) ?></th>
                            <th scope="col" class="col actions"><?= $block->escapeHtml(__('VIEWRECORDER')) ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($_orders as $_order) : ?>
                            <?php
                            $status = $_order->getStatus();
                            $statusLabel = '';
                            $statusColor = '';

                            switch ($status) {
                                case 'pending':
                                    $statusLabel = 'Neapmaksāts';
                                    $statusColor = 'bg-customRed'; // Red for not paid
                                    break;
                                case 'processing':
                                    $statusLabel = 'Gaida';
                                    $statusColor = 'bg-statusYellow'; // Yellow for waiting
                                    break;
                                case 'complete':
                                    $statusLabel = 'Apmaksāts';
                                    $statusColor = 'bg-statusGreen'; // Green for paid
                                    break;
                                default:
                                    $statusLabel = 'N/A';
                                    $statusColor = 'bg-gray-500'; // Default color for unknown status
                            }
                            ?>
                            <tr class="h-12 border-b border-paleGray text-center text-sm">
                                <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id text-customRed"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
                                <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date text-customDark"><?= $block->escapeHtml($block->formatDate($_order->getCreatedAt())) ?></td>
                                <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col shipping text-customDark"><?= $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : "&nbsp;" ?></td>
                                <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total text-customDark font-bold"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                                <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status">
                                    <span class="inline-block w-2.5 h-2.5 rounded-full mr-2 <?= $statusColor ?>"></span>
                                    <?= $block->escapeHtml($statusLabel) ?>
                                </td>
                                <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                                    <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                                        <img src="<?= $block->getViewFileUrl('images/icons/Eye.svg') ?>" class="w-5 h-5 inline-block mr-2" alt="View">
                                    </a>
                                    <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
                                        <a href="#" data-post='<?= /* @noEscape */
                                        $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)->getPostData($block->getReorderUrl($_order))
                                        ?>' class="action order">
                                            <img src="<?= $block->getViewFileUrl('images/icons/Reorder.svg') ?>" class="w-5 h-5 inline-block mr-2" alt="Reorder">
                                        </a>
                                    <?php endif ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php else : ?>
            <div class="message info empty"><span><?= $block->escapeHtml(__('You have placed no orders.')) ?></span></div>
        <?php endif; ?>
    </div>
    <div class="block-title order p-8">
        <?php if ($count > 0) : ?>
            <a class="action view inline-block px-6 py-3 bg-customRed text-white font-semibold text-sm hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500" href="<?= $block->escapeUrl($block->getUrl('sales/order/history')) ?>">
                <span><?= $block->escapeHtml(__('SKATĪT VISU')) ?></span>
            </a>
        <?php endif; ?>
    </div>
</div>