<div class="account-nav border border-gray-300 bg-customGray">
    <ul class="space-y-2">
        <li class="h-15 flex items-center border-l-4 border-customRed bg-gradient-to-r from-paleRed to-customGray">
            <a href="<?= $block->escapeUrl($block->getUrl('customer/account')) ?>" class="text-blue-600 p-6">Mans profils</a>
        </li>
        <li class="h-15 flex items-center"><a href="<?= $block->escapeUrl($block->getUrl('customer/address')) ?>" class="text-blue-600 p-6">Adrešu grāmata</a></li>
        <li class="h-15 flex items-center"><a href="<?= $block->escapeUrl($block->getUrl('sales/order/history')) ?>" class="text-blue-600 p-6">Mani pasūtījumi</a></li>
        <li class="h-15 flex items-center"><a href="<?= $block->escapeUrl($block->getUrl('customer/contracts')) ?>" class="text-blue-600 p-6">Mani līgumi</a></li>
        <li class="h-15 flex items-center"><a href="<?= $block->escapeUrl($block->getUrl('customer/payment-methods')) ?>" class="text-blue-600 p-6">Saglabātie maksājuma veidi</a></li>
        <li class="h-15 flex items-center"><a href="<?= $block->escapeUrl($block->getUrl('customer/privacy-settings')) ?>" class="text-blue-600 p-6">Privātuma uzstādījumi</a></li>
        <li class="h-15 flex items-center"><a href="<?= $block->escapeUrl($block->getUrl('customer/company-info')) ?>" class="text-blue-600 p-6">Uzņēmuma informācija</a></li>
        <li class="h-15 flex items-center"><a href="<?= $block->escapeUrl($block->getUrl('customer/company-users')) ?>" class="text-blue-600 p-6">Uzņēmuma lietotāji</a></li>
        <li class="h-15 flex items-center"><a href="<?= $block->escapeUrl($block->getUrl('customer/user-permissions')) ?>" class="text-blue-600 p-6">Lietotāju tiesības</a></li>
        <li class="h-15 flex items-center"><a href="<?= $block->escapeUrl($block->getUrl('customer/credit-limit')) ?>" class="text-blue-600 p-6">Kredītlimīts</a></li>
        <li class="h-15 flex items-center"><a href="<?= $block->escapeUrl($block->getUrl('customer/account/logout')) ?>" class="text-red-600 p-6">Logout</a></li>
    </ul>
</div>
